[package]
authors = ["Garrett Berg <vitiral@gmail.com>"]
description = "Artifact is a design doc tool made for developers. It allows anyone to\neasily write and link their design docs both to each other and to source code,\nmaking it easy to track how complete their project is.\nDocuments are revision controllable, can be rendered as a static\nweb page and have a full suite of command line tools for searching,\nformatting and displaying them.\n"
documentation = "http://vitiral.github.io/artifact/"
keywords = ["cmdline", "tool", "requirements", "documentation", "testing"]
license = "LGPL-3.0+"
name = "artifact-app"
readme = "README.md"
repository = "https://github.com/vitiral/artifact"
version = "0.6.5"

[dependencies]
ansi_term = "0.7"
chrono = "0.3.0"
difference = "1.0"
fern = "0.3.5"
itertools = "0.5"
lazy_static = "0.1.*"
log = "0.3.6"
regex = "0.2.1"
rustc-serialize = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
strfmt = "0.1"
tar = "0.4"
tempdir = "0.3"
time = "0.1"
toml = "0.2"
unicode-segmentation = "1.1.0"
unicode-width = "0.1.4"

[dependencies.clap]
default-features = false
features = ["suggestions", "color", "wrap_help"]
version = "2"

[dependencies.diesel]
features = ["postgres", "chrono"]
optional = true
version = "0.11.0"

[dependencies.diesel_codegen]
features = ["postgres"]
optional = true
version = "0.11.0"

[dependencies.dotenv]
optional = true
version = "0.8.0"

[dependencies.error-chain]
default-features = true
version = "0.9.0"

[dependencies.jsonrpc-core]
optional = true
version = "6.0.0"

[dependencies.nickel]
optional = true
version = "0.9"

[dependencies.tabwriter]
default-features = false
features = ["ansi_formatting"]
version = "1.0.3"


[dev-dependencies]
fs_extra = "1.0.0"

[features]
default = []
server = ["nickel", "jsonrpc-core", "diesel", "diesel_codegen", "dotenv"]

[profile]

[profile.dev]
codegen-units = 3
