artifact_paths = ["{repo}/design"]

exclude_artifact_paths = []

code_paths = [
    "/artifact-app/src",
    "/artifact-app/tests",
    "/artifact-lib/src",
    "/artifact-ser/src",
    "/artifact-data/src",
    "/artifact-test/src",
    "/artifact-frontend/src",
]

exclude_code_paths = [
]

code_url = "https://github.com/vitiral/artifact/blob/master/{file}#L{line}"

[export]
md_header = """
Artifact design docs, exported to markdown.

See [REQ-purpose](#REQ-PURPOSE) for the top level artifact.

> Note: Export docs like this with `art export md exported.md`
>
> Settings are in `.art/settings.toml`
"""
md_family = { type = "list" }

[export.md_dot]
type = "ignore"
# pre = """
# ![Alt text](https://g.gravizo.com/source/custom_mark10?https%3A%2F%2Fraw.githubusercontent.com%2FTLmaK0%2Fgravizo%2Fmaster%2FREADME.md)
# <details>
# <summary></summary>
# custom_mark10
# """
# post = """
# custom_mark10
# </details>
# """
